# Generated by Django 5.1.1 on 2024-09-24 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioGrupoSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
                ('grupo_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gruposkill')),
            ],
            options={
                'unique_together': {('funcionario', 'grupo_skill')},
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='grupos_skills',
            field=models.ManyToManyField(through='core.FuncionarioGrupoSkill', to='core.gruposkill'),
        ),
    ]
