# Generated by Django 5.1.1 on 2024-10-08 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='grupos_skills',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='comprovacao_treinamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='skills',
            field=models.ManyToManyField(related_name='funcionarios', to='core.skill'),
        ),
        migrations.DeleteModel(
            name='FuncionarioGrupoSkill',
        ),
        migrations.DeleteModel(
            name='GrupoSkill',
        ),
    ]
