# Generated by Django 5.1.1 on 2024-11-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarioskill',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='funcionarioskill',
            unique_together={('funcionario', 'skill')},
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('finalizado', models.BooleanField(default=False)),
                ('funcionarios', models.ManyToManyField(related_name='treinamentos', to='core.funcionario')),
                ('skills', models.ManyToManyField(related_name='treinamentos', to='core.skill')),
            ],
        ),
    ]
