# Generated by Django 5.1.1 on 2024-11-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_funcionarioskill_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='nome',
        ),
    ]
