# Generated by Django 5.1.1 on 2024-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_treinamento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='competencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='escopo_atividade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
